name = "vestrocloud-coming-soon"
compatibility_date = "2023-12-01"

[build]
command = "npm run build"

[site]
bucket = "./out"

# Specify the output directory for Pages
pages_build_output_dir = "out"
